Repository LoginRadius/awesome-login-pages, pull requests merged in 2021-10, with the labels that each got.

#10 Added new Login Page v13
  README.md
  login-form-v13/css/main.css
  login-form-v13/images/bg-01.jpg
  login-form-v13/index.html
  login-form-v13/screenshot.png
Labels: Hacktoberfest

#8 added new login page
  README.md
  login-form-ver1/login-form-ver1/My.jpg
  login-form-ver1/login-form-ver1/Web-Development.jpg
  login-form-ver1/login-form-ver1/index.html
  login-form-ver1/login-form-ver1/screenshot.PNG
  login-form-ver1/login-form-ver1/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted

#14 Updates to README
  README.md
  login-form-01/login-form-01/screenshotmobile.png
  login-form-02/login-form-02/screenshotmobile.png
  login-form-03/login-form-03/screenshotmobile.png
  login-form-04/login-form-04/screenshotmobile.png
  login-form-05/login-form-05/screenshotmobile.png
  login-form-06/login-form-06/screenshotmobile.png
  login-form-v14/index.html
  login-form-v14/screenshot.PNG
Labels: Hacktoberfest, hacktoberfest-accepted

#35 Added new login form login-form-v17
  README.md
  login-form-v17/desktop_screenshot.PNG
  login-form-v17/index.html
  login-form-v17/mobile_screenshot.PNG
  login-form-v17/style.css
Labels: hacktoberfest-accepted

#46 Added Create new account option
  login-form-13/login-form-13/index.html
Labels: hacktoberfest-accepted

#49 Add contributors section readme
  README.md
Labels: hacktoberfest-accepted

#52 add login-form-18
  README.md
  login-form-18/Screenshot_1.png
  login-form-18/Screenshot_2.png
  login-form-18/login-form-18/css/style.css
  login-form-18/login-form-18/index.html
Labels: hacktoberfest-accepted

#153 login-form-33
  README.md
  login-form-33/index.html
  login-form-33/main.js
  login-form-33/preview-desktop.png
  login-form-33/preview-mobile.png
  login-form-33/style.css
Labels: hacktoberfest-accepted

#155 Added a login page under the name "login-page-with-social-media"
  README.md
  login-page-with-social-media/Desktop.png
  login-page-with-social-media/Mobile.png
  login-page-with-social-media/index.html
  login-page-with-social-media/style.css
Labels: hacktoberfest-accepted
